# Generated by Django 4.0.4 on 2022-04-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.TextField()),
                ('brief_content', models.TextField()),
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
